.TH "GISTI" "1" "October 2020" "" "GISTI Help"
.SH "NAME"
\fBGISTI\fR
.QP
.P
GistI(nteractive) \- The interactive CLI for gist

.
.P
To learn more, visit https://github\.com/pascalrogalla/gisti \fIhttps://github\.com/pascalrogalla/gisti\fR
.SH DESCRIPTION
.P
Gisti is a command line tool that supports interactive gist handling in your terminal\.
.SH WHY?
.P
Inspired by \fByarn upgrade\-interactive\fP,
.P
this interactive command line tool is designed to act with github gists in an easy way\.
.SH Install
.SS npm
.P
\fBnpm install \-g gist\fP
.SS yarn
.P
\fByarn global add gisti\fP
.SH Usage
.P
\fBgisti [options] [command]\fP
.P
.RS 2
.nf
Options:
  \-V, \-\-version                output the version number
  \-h, \-\-help                   output usage information

Commands:
  auth [options] [token]       Sets/Updates the personal access token
  list [options]               List your gists
  copy [options]               Copies the id of a gist to the clipboard
  open [options] [id]          Opens a gist in your browser
  create [options] <files\.\.\.>  Creates a new gist
  download [options] [id]      Downloads a gist or gist file
  search [options] [query]     Searches for gists
  delete [options] [id]        Deletes a gist from github
.fi
.RE
.SS Auth
.P
\fBgisti auth [options] [token]\fP
.P
.RS 2
.nf
Options:
  \-t, \-\-token <token>  Set token
  \-h, \-\-help           output usage information
.fi
.RE
.SS List
.P
\fBgisti list [options]\fP
.P
.RS 2
.nf
Options:
  \-x, \-\-private  List private Gists
  \-s, \-\-starred  List starred Gists
  \-p, \-\-public   List public Gists
  \-f, \-\-files    List files of Gist
  \-h, \-\-help     output usage information
.fi
.RE
.SS Copy
.P
\fBgisti copy [options]\fP
.P
.RS 2
.nf
Options:
  \-x, \-\-private  List private Gists
  \-s, \-\-starred  List starred Gists
  \-p, \-\-public   List public Gists
  \-h, \-\-help     output usage information
.fi
.RE
.SS Open
.P
\fBgisti open [options] [id]\fP
.P
.RS 2
.nf
Options:
  \-\-id <id>      Gist id for non\-interactive update
  \-x, \-\-private  List private Gists
  \-s, \-\-starred  List starred Gists
  \-p, \-\-public   List public Gists
  \-h, \-\-help     output usage information
.fi
.RE
.SS Create
.P
\fBgisti create [options] <files\.\.\.>\fP
.P
.RS 2
.nf
Options:
  \-x, \-\-private                    Create private Gist
  \-p, \-\-public                     Create public Gists
  \-d, \-\-description <description>  Set the gist description
  \-h, \-\-help                       output usage information
.fi
.RE
.SS Download
.P
\fBgisti download [options] [id]\fP
.P
.RS 2
.nf
Options:
  \-\-id <id>      Gist id
  \-x, \-\-private  List private Gists
  \-s, \-\-starred  List starred Gists
  \-p, \-\-public   List public Gists
  \-h, \-\-help     output usage information
.fi
.RE
.SS Download
.P
\fBgisti search [options] [query]\fP
.P
.RS 2
.nf
Options:
  \-l, \-\-list      List search result
  \-c, \-\-copy      Copy the id of one resulted gist
  \-o, \-\-open      Open one resulted gist in browser
  \-d, \-\-download  Download resulted gists
  \-h, \-\-help      output usage information
.fi
.RE
.SS Delete
.P
\fBgisti delete [options] [id]\fP
.P
.RS 2
.nf
Options:
  \-x, \-\-private  List private Gists
  \-p, \-\-public   List public Gists
  \-h, \-\-help     output usage information
.fi
.RE
.SH Website
.P
https://github\.com/pascalrogalla/gisti \fIhttps://github\.com/pascalrogalla/gisti\fR
.SH CONFIGURATION
.P
Add your github personal token
.P
\fBgisti auth [token]\fP
.SH BUGS
.P
Please report any bugs to https://github\.com/pascalrogalla/gisti/issues
.SH LICENSE
.P
Copyright (c) 2019, Pascal Rogalla (MIT License)\.

