.TH "GISTI" "1" "October 2020" "v1.0.0" "GISTI Help"
.SH "NAME"
\fBGISTI\fR
.QP
.P
GISTI \- The interactive CLI for gist

.
.P
To learn more, visit https://github\.com/pascalrogalla/gisti \fIhttps://github\.com/pascalrogalla/gisti\fR
.SH SYNOPSIS
.P
\fBgisti [\-l, \-\-list] [\-d, \-\-download] [\-o, \-\-open] [\-s, \-\-starred] [\-p, \-\-private] [\-v] [\-h]\fP
.SH DESCRIPTION
.P
Gisti is a command line tool that supports interactive gist handling in your terminal\.
.SH Website
.P
https://github\.com/pascalrogalla/gisti \fIhttps://github\.com/pascalrogalla/gisti\fR
.SH EXAMPLES
.P
\fBnpm install gisti \-g\fP
.P
\fBgisti \-l\fP
.P
\fBgisti \-l \-p\fP
.P
\fBgisti \-d \-s\fP
.P
\fBgisti \-h\fP
.P
\fBgisti \-v\fP
.SH OPTIONS
.P
\fB\-\-list\fP, \fB\-i\fP
List your gists
.P
\fB\-\-download\fP, \fB\-d\fP
Download a gist
.P
\fB\-\-open\fP, \fB\-o\fP \fB[id]\fP
Open a gist in your browser
.P
\fB\-\-starred\fP, \fB\-s\fP
Just show starred gists for list, download or open
.P
\fB\-\-private\fP, \fB\-p\fP
Just show private gists for list, download or open
.P
\fB\-\-version\fP, \fB\-v\fP
Display the version of Gisti
.P
\fB\-\-help\fP, \fB\-h\fP
Show this help
.SH CONFIGURATION
.P
Add your github personal token
\fBgisti \-\-token [token]\fP
.SH BUGS
.P
Please report any bugs to https://github\.com/pascalrogalla/gisti\.
.SH LICENSE
.P
Copyright (c) 2019, Pascal Rogalla (MIT License)\.
.SH SEE ALSO
.P
https://github\.com/defunkt/gist
.P
https://github\.com/jrbasso/gistit/

